// File __EUNIT_TestControl_Lab2_BF609EUNIT_Core0.cpp generated by E-UNIT program
// Author: aidan
// Date: Thu 2019/11/21 at 10:55:00 AM

#define HUMAN_INTERVENTION_TEST_LEVEL 20
#define ALL_TEST_LEVELS 0xFFFF

void AutomatedTestLevelControl(void)
{
    return;
}