// File __EUNIT_TestControl_HelloWorld_Sim533.cpp generated by E-UNIT program
// Author: aidan
// Date: Wed 2019/10/30 at 10:20:29 PM

#define HUMAN_INTERVENTION_TEST_LEVEL 20
#define ALL_TEST_LEVELS 0xFFFF

void AutomatedTestLevelControl(void)
{
    return;
}