// File __EUNIT_TestControl_Assignment1WithCoreTimerEUNIT_Sim533.cpp generated by E-UNIT program
// Author: aidan
// Date: Sun 2019/11/24 at 01:22:27 PM

#define HUMAN_INTERVENTION_TEST_LEVEL 20
#define ALL_TEST_LEVELS 0xFFFF

void AutomatedTestLevelControl(void)
{
    return;
}